version: '3'
services:
  api: &prod
    restart: unless-stopped
    build: .
    image: logs-dashboard-api
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - prod
    volumes:
      - ./:/api
    env_file:
      - docker.env

  db:
    image: postgres:14
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - prod
    env_file:
      - ./docker.env

networks:
  prod:
  test:
